export const NOTIFICATION_TYPES = {
  INTEREST_RECEIVED: "INTEREST_RECEIVED",
  INTEREST_ACCEPTED: "INTEREST_ACCEPTED",
  INTEREST_DECLINED: "INTEREST_DECLINED",
  HIGH_MATCH: "HIGH_MATCH",
  NEW_MESSAGE: "NEW_MESSAGE",
};

export const NOTIFICATION_TYPE_VALUES = Object.values(NOTIFICATION_TYPES);

