export const USER_ROLES = {
  TENANT: "TENANT",
  OWNER: "OWNER",
  ADMIN: "ADMIN",
};

export const USER_ROLE_VALUES = Object.values(USER_ROLES);
export const PUBLIC_REGISTER_ROLE_VALUES = [USER_ROLES.TENANT, USER_ROLES.OWNER];
